### ISSUE TITLE
Make all example apps to run

### ISSUE THREAD

**Issue by jban332** [jban332/flutter2js#1]

**Comment by realcarlos** [comment]
I followed the doc ,but all example apps could not run now.

the error is : 

[Warning from Dart2JS on stocks_browser|web/main.dart]:
web/packages/stocks/stock_home.dart:10:9:
Library 'package:flutter/rendering.dart' doesn't export a 'debugDumpSemanticsTree' declaration.
Try removing 'debugDumpSemanticsTree' from the 'show' clause.
        debugDumpSemanticsTree,
        ^^^^^^^^^^^^^^^^^^^^^^
[Error from Dart2JS on stocks_browser|web/main.dart]:
web/packages/flutter/src/material/flat_button.dart:65:8:
Expected an expression, but got 'assert'.
  }) : assert(child != null),
       ^^^^^^
[Dart2JS on stocks_browser|web/main.dart]:
1 warning(s) suppressed in package:flur.
[Dart2JS on stocks_browser|web/main.dart]:
1 warning(s) and 1 hint(s) suppressed in package:flutter.
[Dart2JS on stocks_browser|web/main.dart]:
1 warning(s) suppressed in package:flur_html.
[Dart2JS on stocks_browser|web/main.dart]:
3 warning(s) suppressed in package:stocks.
[Info from Dart2JS]:
Took 0:00:07.957564 to compile stocks_browser|web/main.dart.
Build completed with 1 errors.
[web] GET main.dart.js → Could not find asset stocks_browser|web/main.dart.js.
