### ISSUE TITLE
Continuing ?

### ISSUE THREAD

**Issue by gedw99** [jban332/flutter2js#2]
You got a fair way through on this.
I was surprised how much reuse you got and how little it took for new code.

Also flutter and other dart packages are starting to use built value package which will unify the flux / reflux stuff and so make this much more viable.

Any thoughts on moving forward ?
What can I do to help ?

I was thinking that targeting webgl would be smarter because flutter and skia is using OpenGL and so there is less work to do. I guess you also considered that approach ?

Don't you need some of flutter/engine ? I guess not.

Anyway curious to hear your thoughts...

**Comment by jban332** [comment]
Directly drawing rendering tree (with WebGL or Canvas) would mean losing lots of functionality implemented by browsers such as copy-pasting, spell correction, and scrolling.

This project contains "dart:ui" from "flutter/engine".
